opt_in_rules:
 - sorted_imports

custom_rules:
  double_spaces:
    name: "Double spaces inside lines"
    regex: "\\w {2,}\\w"   # 2 or more consecutive spaces
    message: "Extra double spaces"
    severity: warning

line_length:
  warning: 300  # Set a warning when lines exceed 300 characters
type_body_length:
  warning: 500  # Set a warning when a type body exceeds 500 lines
file_length:
  warning: 750  # Set a warning when a file exceeds 750 lines

disabled_rules:
  - void_function_in_ternary
  - redundant_string_enum_value

function_parameter_count:
  warning: 10
  error: 15

nesting:
  type_level:
    warning: 2
    error: 3

excluded:
  - .git
  - Pods
  - Carthage
